services:
  app:
    image: app
    build:
      context: ./app
      dockerfile: Dockerfile
      target: dev
    ports:
      - 5173:5173
    develop:
      watch:
        - path: app/package.json
          action: rebuild
        - path: app
          action: sync
          target: /app
          ignore:
            - app/node_modules
  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8000:8000
    develop:
      watch:
        - path: api/compose.json
          action: rebuild
        - path: api/
          action: sync
          target: /www/app/
    env_file:
      - ./api/.env
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=hello
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis/redis-stack:latest
    ports:
      - 8001:8001
      - 6379:6379
    volumes:
      - redis:/data
  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
    volumes:
      - ./mailpit.db:/data/mailpit.db
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1 
  worker:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    command: php artisan queue:work
    env_file:
      - ./api/.env
    depends_on:
      - db
      - redis

volumes:
  db:
  redis:
